# Generated by Django 2.0 on 2018-05-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180514_1445'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='is_public',
        ),
    ]
