# Generated by Django 2.0 on 2018-05-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180516_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
