# Generated by Django 2.0 on 2018-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
